# Generated by Django 3.1.1 on 2020-11-19 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', default=1)),
                ('airline', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', default=1)),
                ('code', models.CharField(max_length=8, null=True)),
                ('duration', models.CharField(max_length=20, null=True)),
                ('time', models.DateTimeField()),
                ('fromdest', models.CharField(max_length=20, null=True)),
                ('todest', models.CharField(max_length=20, null=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.airlines')),
            ],
        ),
    ]
