# Generated by Django 3.1.1 on 2020-11-19 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_airlines_flights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('stars', models.IntegerField()),
                ('pets', models.CharField(max_length=10, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.location')),
            ],
        ),
    ]
