# Generated by Django 3.1.1 on 2020-11-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201120_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flights',
            options={'ordering': ['time']},
        ),
        migrations.AddField(
            model_name='flights',
            name='ns',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='nslb',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='nsle',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='nslf',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='obw',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
