# Generated by Django 3.1.1 on 2020-11-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201122_2100'),
        ('store', '0005_auto_20201122_2215'),
    ]

    operations = [
    ]
