# Generated by Django 3.1.1 on 2020-11-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_merge_20201123_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name']},
        ),
    ]
