# Generated by Django 3.1.1 on 2020-11-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201123_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='apt_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='baggage_lim',
            field=models.IntegerField(null=True),
        ),
    ]
