# Generated by Django 3.1.1 on 2020-11-25 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201124_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.flights')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pas_name', models.CharField(max_length=50, null=True)),
                ('pas_age', models.IntegerField(null=True)),
                ('pas_gen', models.CharField(max_length=10, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ticket')),
            ],
        ),
    ]
