# Generated by Django 3.1.1 on 2020-11-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_details_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pas1_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pas1_gen',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pas1_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pas2_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pas2_gen',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pas2_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pas3_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pas3_gen',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pas3_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pas4_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pas4_gen',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pas4_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pas5_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pas5_gen',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pas5_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
