# Generated by Django 3.1.1 on 2020-11-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20201126_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flights',
            old_name='price',
            new_name='price_b',
        ),
        migrations.AddField(
            model_name='flights',
            name='price_e',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='flights',
            name='price_fc',
            field=models.IntegerField(default=5000),
        ),
    ]
