# Generated by Django 3.1.1 on 2020-11-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20201127_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='cpn',
        ),
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='no_spl',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='no_std',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='no_suite',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='parking',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='pool',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_spl',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_std',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_suite',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='wifi',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.FloatField(default=4.0),
        ),
    ]
