# Generated by Django 3.1.1 on 2020-11-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20201128_1444'),
        ('store', '0015_auto_20201128_1250'),
    ]

    operations = [
    ]
