# Generated by Django 3.1.1 on 2020-11-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_merge_20201129_1127'),
        ('store', '0016_merge_20201128_2353'),
    ]

    operations = [
    ]
