# Generated by Django 3.1.1 on 2020-11-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_merge_20201129_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='numrooms',
            field=models.IntegerField(default=2),
        ),
    ]
