# Generated by Django 3.1.1 on 2020-11-29 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0018_hotel_numrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gues1_name', models.CharField(max_length=50, null=True)),
                ('gues1_age', models.IntegerField(null=True)),
                ('gues1_gen', models.CharField(max_length=10, null=True)),
                ('gues2_name', models.CharField(max_length=50, null=True)),
                ('gues2_age', models.IntegerField(null=True)),
                ('gues2_gen', models.CharField(max_length=10, null=True)),
                ('gues3_name', models.CharField(max_length=50, null=True)),
                ('gues3_age', models.IntegerField(null=True)),
                ('gues3_gen', models.CharField(max_length=10, null=True)),
                ('gues4_name', models.CharField(max_length=50, null=True)),
                ('gues4_age', models.IntegerField(null=True)),
                ('gues4_gen', models.CharField(max_length=10, null=True)),
                ('gues5_name', models.CharField(max_length=50, null=True)),
                ('gues5_age', models.IntegerField(null=True)),
                ('gues5_gen', models.CharField(max_length=10, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.hotel')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
