# Generated by Django 3.1.1 on 2020-12-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_rooms_no_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='img_1',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='hotel',
            name='img_2',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
