# Generated by Django 3.1.1 on 2020-12-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20201204_1059'),
        ('store', '0023_auto_20201204_1347'),
    ]

    operations = [
    ]
